services:
  api:
      build: .
      container_name: familytree_app
      command: uvicorn familytree.main:app --host 0.0.0.0 --port 8000
      ports:
        - "127.0.0.1:8008:8000"
      depends_on:
        - db
      env_file:
        - .env
      environment:
        - TZ=Asia/Yekaterinburg 
      volumes:
        - ./static:/app/static
        - ./logs:/app/logs 
      restart: always

  db:
    image: postgres:18
    container_name: familytreedb
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always

volumes:
  postgres_data: