"""add year column to photos

Revision ID: 5b3b465a3ba9
Revises: 3b225c9b1c43
Create Date: 2026-03-11 17:44:18.982519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b3b465a3ba9'
down_revision: Union[str, Sequence[str], None] = '3b225c9b1c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'year')
    # ### end Alembic commands ###
